export enum PaymentMethod {
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  NET_BANKING = 'NET_BANKING',
  UPI = 'UPI',
  AMAZON_PAY = 'AMAZON_PAY',
  COD = 'COD',
}

export enum ShippingSpeed {
  STANDARD = 'STANDARD',
  EXPEDITED = 'EXPEDITED',
  TWO_DAY = 'TWO_DAY',
  ONE_DAY = 'ONE_DAY',
  SAME_DAY = 'SAME_DAY',
}

export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  SELLER = 'SELLER',
  ADMIN = 'ADMIN',
}

export enum MembershipTier {
  FREE = 'FREE',
  PRIME = 'PRIME',
  PRIME_STUDENT = 'PRIME_STUDENT',
  PRIME_BUSINESS = 'PRIME_BUSINESS',
  BUSINESS = 'BUSINESS',
}

export enum ProductCategory {
  ELECTRONICS = 'ELECTRONICS',
  BOOKS = 'BOOKS',
  FASHION = 'FASHION',
  HOME_KITCHEN = 'HOME_KITCHEN',
  BEAUTY_PERSONAL_CARE = 'BEAUTY_PERSONAL_CARE',
  TOYS_GAMES = 'TOYS_GAMES',
  SPORTS_OUTDOORS = 'SPORTS_OUTDOORS',
  AUTOMOTIVE = 'AUTOMOTIVE',
  GROCERY_WHOLE_FOODS = 'GROCERY_WHOLE_FOODS',
  HEALTH_HOUSEHOLD = 'HEALTH_HOUSEHOLD',
  OFFICE_PRODUCTS = 'OFFICE_PRODUCTS',
  PET_SUPPLIES = 'PET_SUPPLIES',
  TOOLS_HOME_IMPROVEMENT = 'TOOLS_HOME_IMPROVEMENT',
}

export enum ProductCondition {
  NEW = 'NEW',
  USED_LIKE_NEW = 'USED_LIKE_NEW',
  USED_VERY_GOOD = 'USED_VERY_GOOD',
  USED_GOOD = 'USED_GOOD',
  USED_ACCEPTABLE = 'USED_ACCEPTABLE',
  REFURBISHED = 'REFURBISHED',
}

export enum ProductAvailability {
  IN_STOCK = 'IN_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  PRE_ORDER = 'PRE_ORDER',
  DISCONTINUED = 'DISCONTINUED',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}
