// frontend/src/services/mockData.ts

export const mockProducts = [
    // ========== ELECTRONICS (8 Products with Realistic Images) ==========
    {
        id: 'prod-001',
        asin: 'B08N5WRWNW',
        title: 'Wireless Bluetooth Headphones - Premium Sound Quality with Active Noise Cancellation',
        subtitle: 'Crystal Clear Audio for Calls & Learning',
        brand: 'AudioTech',
        manufacturer: 'AudioTech Inc.',
        description: 'Experience premium sound with these wireless Bluetooth headphones featuring active noise cancellation, 40-hour battery life, and ultra-comfortable memory foam ear cushions.',
        bulletPoints: ['🎧 Premium Hi-Fi Sound for Clear Voice & Lectures', '🔇 Active Noise Cancellation for Focused Study', '🔋 40 Hours Battery Life with Quick Charge', '📞 Built-in HD Microphone for Clear Calls', '💻 Perfect for Online Classes & Work Meetings'],
        category: 'ELECTRONICS',
        subCategory: 'Headphones',
        pricing: { basePrice: 149.99, salePrice: 99.99, compareAtPrice: 199.99, savingsPercentage: 50, isOnSale: true, couponDiscount: 10, primePrice: 89.99, currency: 'USD' },
        totalQuantity: 150,
        condition: 'NEW',
        availability: 'IN_STOCK',
        rating: 4.5,
        reviewCount: 2341,
        isPrimeEligible: true,
        isBestSeller: true,
        isAmazonChoice: true,
        sellerId: 'user-004',
        sellerName: 'AudioTech Official',
        sellerRating: 4.8,
        images: [
            { id: 'img-1', url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop', thumbnailUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=100&h=100&fit=crop', altText: 'Wireless Bluetooth Headphones', isPrimary: true, order: 0 },
        ],
        dimensions: { length: 7.5, width: 6.5, height: 3.2, weight: 250, unit: 'in', weightUnit: 'g' },
        shipping: { freeShipping: true, estimatedDelivery: { standard: { minDays: 3, maxDays: 5, businessDays: true } }, shipsFrom: 'US', internationalShipping: true },
        amazonFeatures: { isPrimeEligible: true, isAmazonChoice: true, isBestSeller: true, isAmazonBrand: false, hasCoupon: true, couponValue: 10, couponType: 'percentage', isSubscribeAndSave: false, isClimatePledgeFriendly: true, isAlexaEnabled: false, isAmazonFresh: false, tradeInEligible: false },
        badges: [{ type: 'BEST_SELLER', text: 'Best Seller' }, { type: 'AMAZON_CHOICE', text: "Amazon's Choice" }],
        originCountry: 'China',
        createdAt: '2024-01-15T00:00:00Z',
        updatedAt: '2024-06-01T00:00:00Z',
    },
    {
        id: 'prod-003',
        asin: 'B08N5WRWNY',
        title: 'Ergonomic Aluminum Laptop Stand - Adjustable Holder for Desk Setup',
        subtitle: 'Perfect for Work & Study',
        brand: 'TechPro',
        manufacturer: 'TechPro Accessories',
        description: 'Premium aluminum laptop stand with 7 adjustable height levels. Ergonomic design improves posture and provides optimal airflow.',
        bulletPoints: ['🔧 7 Adjustable Height Levels', '💨 Open Design for Maximum Airflow', '🛡️ Sturdy Aluminum Construction', '📱 Fits 10-17 inch Laptops', '✨ Sleek Space Gray Finish'],
        category: 'ELECTRONICS',
        subCategory: 'Computer Accessories',
        pricing: { basePrice: 79.99, salePrice: 59.99, compareAtPrice: 99.99, savingsPercentage: 40, isOnSale: true, currency: 'USD' },
        totalQuantity: 200,
        condition: 'NEW',
        availability: 'IN_STOCK',
        rating: 4.3,
        reviewCount: 892,
        isPrimeEligible: false,
        isBestSeller: false,
        isAmazonChoice: false,
        sellerId: 'user-004',
        sellerName: 'TechPro Store',
        sellerRating: 4.2,
        images: [
            { id: 'img-1', url: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=400&h=400&fit=crop', thumbnailUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=100&h=100&fit=crop', altText: 'Laptop Stand', isPrimary: true, order: 0 },
        ],
        dimensions: { length: 10, width: 9, height: 6, weight: 800, unit: 'in', weightUnit: 'g' },
        shipping: { freeShipping: false, shippingCost: 5.99, estimatedDelivery: { standard: { minDays: 5, maxDays: 10, businessDays: true } }, shipsFrom: 'China', internationalShipping: true },
        amazonFeatures: { isPrimeEligible: false, isAmazonChoice: false, isBestSeller: false, isAmazonBrand: false, hasCoupon: false, isSubscribeAndSave: false, isClimatePledgeFriendly: false, isAlexaEnabled: false, isAmazonFresh: false, tradeInEligible: false },
        badges: [{ type: 'SALE', text: '40% OFF' }],
        originCountry: 'China',
        createdAt: '2024-03-10T00:00:00Z',
        updatedAt: '2024-05-20T00:00:00Z',
    },
    {
        id: 'prod-006',
        asin: 'B08N5WRWOB',
        title: '4K Webcam with Ring Light - Professional Streaming Camera',
        subtitle: 'Crystal Clear Video for Calls & Classes',
        brand: 'StreamPro',
        manufacturer: 'StreamPro Tech',
        description: 'Professional 4K webcam with built-in ring light and auto-focus. Perfect for video calls, online classes, and work meetings.',
        bulletPoints: ['📸 4K Ultra HD Resolution', '💡 Built-in Ring Light with 3 Levels', '🎯 Auto-Focus Technology', '🔌 Plug & Play USB Connection', '🖥️ Works with Zoom, Skype, Teams'],
        category: 'ELECTRONICS',
        subCategory: 'Webcams',
        pricing: { basePrice: 129.99, salePrice: 89.99, compareAtPrice: 159.99, savingsPercentage: 44, isOnSale: true, currency: 'USD' },
        totalQuantity: 75,
        condition: 'NEW',
        availability: 'IN_STOCK',
        rating: 4.7,
        reviewCount: 678,
        isPrimeEligible: true,
        isBestSeller: false,
        isAmazonChoice: true,
        sellerId: 'user-004',
        sellerName: 'StreamPro Official',
        sellerRating: 4.5,
        images: [
            { id: 'img-1', url: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400&h=400&fit=crop', thumbnailUrl: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=100&h=100&fit=crop', altText: '4K Webcam', isPrimary: true, order: 0 },
        ],
        dimensions: { length: 4, width: 3, height: 3, weight: 150, unit: 'in', weightUnit: 'g' },
        shipping: { freeShipping: true, estimatedDelivery: { standard: { minDays: 2, maxDays: 4, businessDays: true } }, shipsFrom: 'US', internationalShipping: true },
        amazonFeatures: { isPrimeEligible: true, isAmazonChoice: true, isBestSeller: false, isAmazonBrand: false, hasCoupon: true, couponValue: 15, couponType: 'percentage', isSubscribeAndSave: false, isClimatePledgeFriendly: false, isAlexaEnabled: false, isAmazonFresh: false, tradeInEligible: false },
        badges: [{ type: 'AMAZON_CHOICE', text: "Amazon's Choice" }],
        originCountry: 'China',
        createdAt: '2024-05-01T00:00:00Z',
        updatedAt: '2024-06-01T00:00:00Z',
    },
    {
        id: 'prod-008',
        asin: 'B08N5WRWOD',
        title: 'Digital Quran Pen Reader - Word-by-Word Recitation with Translation',
        subtitle: 'Learn Quran with Proper Tajweed',
        brand: 'QuranTech',
        manufacturer: 'QuranTech Electronics',
        description: 'Innovative digital Quran pen that recites any verse with proper tajweed. Includes multiple translations and reciter voices. Perfect for children and adults.',
        bulletPoints: ['🖊️ Touch Any Verse for Instant Recitation', '🎙️ Multiple Famous Qari Voices', '🌍 Translations in 25+ Languages', '📖 Includes Complete Quran Book', '🔋 Rechargeable Battery - 10hr Life'],
        category: 'ELECTRONICS',
        subCategory: 'Islamic Electronics',
        pricing: { basePrice: 79.99, salePrice: 59.99, compareAtPrice: 99.99, savingsPercentage: 40, isOnSale: true, primePrice: 54.99, currency: 'USD' },
        totalQuantity: 250,
        condition: 'NEW',
        availability: 'IN_STOCK',
        rating: 4.8,
        reviewCount: 3456,
        isPrimeEligible: true,
        isBestSeller: true,
        isAmazonChoice: false,
        sellerId: 'user-004',
        sellerName: 'QuranTech Official',
        sellerRating: 4.8,
        images: [
            { id: 'img-1', url: 'https://images.unsplash.com/photo-1589998059171-988d0df3a8b3?w=400&h=400&fit=crop', thumbnailUrl: 'https://images.unsplash.com/photo-1589998059171-988d0df3a8b3?w=100&h=100&fit=crop', altText: 'Digital Quran Pen', isPrimary: true, order: 0 },
        ],
        dimensions: { length: 10, width: 8, height: 2, weight: 400, unit: 'in', weightUnit: 'g' },
        shipping: { freeShipping: true, estimatedDelivery: { standard: { minDays: 3, maxDays: 5, businessDays: true } }, shipsFrom: 'US', internationalShipping: true },
        amazonFeatures: { isPrimeEligible: true, isAmazonChoice: false, isBestSeller: true, isAmazonBrand: false, hasCoupon: false, isSubscribeAndSave: false, isClimatePledgeFriendly: false, isAlexaEnabled: false, isAmazonFresh: false, tradeInEligible: false },
        badges: [{ type: 'BEST_SELLER', text: 'Best Seller' }, { type: 'SALE', text: '40% OFF' }],
        originCountry: 'UAE',
        createdAt: '2024-02-15T00:00:00Z',
        updatedAt: '2024-06-01T00:00:00Z',
    },
    {
        id: 'prod-022',
        asin: 'B08N5WRWOR',
        title: 'Fast Wireless Charging Pad - 15W Qi Charger for iPhone & Android',
        subtitle: 'Cable-Free Charging Solution',
        brand: 'TechPro',
        manufacturer: 'TechPro Accessories',
        description: 'Fast 15W wireless charging pad compatible with all Qi-enabled devices. Slim design with LED indicator and overcharge protection.',
        bulletPoints: ['⚡ 15W Fast Charging Speed', '📱 Universal Qi Compatible', '🛡️ Overcharge & Heat Protection', '💡 LED Charging Indicator', '📏 Ultra Slim 5mm Design'],
        category: 'ELECTRONICS',
        subCategory: 'Chargers & Power',
        pricing: { basePrice: 29.99, salePrice: 19.99, compareAtPrice: 39.99, savingsPercentage: 50, isOnSale: true, currency: 'USD' },
        totalQuantity: 300,
        condition: 'NEW',
        availability: 'IN_STOCK',
        rating: 4.4,
        reviewCount: 1567,
        isPrimeEligible: true,
        isBestSeller: false,
        isAmazonChoice: false,
        sellerId: 'user-004',
        sellerName: 'TechPro Store',
        sellerRating: 4.2,
        images: [
            { id: 'img-1', url: 'https://images.unsplash.com/photo-1586816879360-004f5b0c51e5?w=400&h=400&fit=crop', thumbnailUrl: 'https://images.unsplash.com/photo-1586816879360-004f5b0c51e5?w=100&h=100&fit=crop', altText: 'Wireless Charger', isPrimary: true, order: 0 },
        ],
        dimensions: { length: 4, width: 4, height: 0.5, weight: 80, unit: 'in', weightUnit: 'g' },
        shipping: { freeShipping: true, estimatedDelivery: { standard: { minDays: 2, maxDays: 4, businessDays: true } }, shipsFrom: 'US', internationalShipping: true },
        amazonFeatures: { isPrimeEligible: true, isAmazonChoice: false, isBestSeller: false, isAmazonBrand: false, hasCoupon: false, isSubscribeAndSave: false, isClimatePledgeFriendly: false, isAlexaEnabled: false, isAmazonFresh: false, tradeInEligible: false },
        badges: [{ type: 'SALE', text: '50% OFF' }],
        originCountry: 'China',
        createdAt: '2024-05-20T00:00:00Z',
        updatedAt: '2024-06-01T00:00:00Z',
    },
    {
        id: 'prod-023',
        asin: 'B08N5WRWOS',
        title: 'USB-C Hub 7-in-1 Adapter - HDMI 4K, USB 3.0, SD Card Reader',
        subtitle: 'Expand Your Laptop Connectivity',
        brand: 'TechPro',
        manufacturer: 'TechPro Accessories',
        description: 'Compact 7-in-1 USB-C hub with HDMI 4K output, 3 USB 3.0 ports, SD/TF card reader. Perfect for MacBook and laptops with limited ports.',
        bulletPoints: ['🔌 7 Ports in 1 Compact Hub', '📺 4K HDMI Output', '💾 SD & TF Card Reader', '⚡ USB 3.0 Super Speed', '💻 Plug & Play No Drivers'],
        category: 'ELECTRONICS',
        subCategory: 'Computer Accessories',
        pricing: { basePrice: 39.99, salePrice: 29.99, compareAtPrice: 49.99, savingsPercentage: 40, isOnSale: true, currency: 'USD' },
        totalQuantity: 180,
        condition: 'NEW',
        availability: 'IN_STOCK',
        rating: 4.5,
        reviewCount: 2345,
        isPrimeEligible: true,
        isBestSeller: true,
        isAmazonChoice: false,
        sellerId: 'user-004',
        sellerName: 'TechPro Store',
        sellerRating: 4.2,
        images: [
            { id: 'img-1', url: 'https://images.unsplash.com/photo-1625723044792-44de16ccb4e9?w=400&h=400&fit=crop', thumbnailUrl: 'https://images.unsplash.com/photo-1625723044792-44de16ccb4e9?w=100&h=100&fit=crop', altText: 'USB-C Hub', isPrimary: true, order: 0 },
        ],
        dimensions: { length: 4, width: 1.5, height: 0.5, weight: 60, unit: 'in', weightUnit: 'g' },
        shipping: { freeShipping: true, estimatedDelivery: { standard: { minDays: 2, maxDays: 4, businessDays: true } }, shipsFrom: 'US', internationalShipping: true },
        amazonFeatures: { isPrimeEligible: true, isAmazonChoice: false, isBestSeller: true, isAmazonBrand: false, hasCoupon: false, isSubscribeAndSave: false, isClimatePledgeFriendly: false, isAlexaEnabled: false, isAmazonFresh: false, tradeInEligible: false },
        badges: [{ type: 'BEST_SELLER', text: 'Best Seller' }, { type: 'SALE', text: '40% OFF' }],
        originCountry: 'China',
        createdAt: '2024-04-10T00:00:00Z',
        updatedAt: '2024-06-01T00:00:00Z',
    },
    {
        id: 'prod-024',
        asin: 'B08N5WRWOT',
        title: 'Portable Bluetooth Speaker - Waterproof with 24hr Battery Life',
        subtitle: 'Rich Sound for Study & Outdoors',
        brand: 'AudioTech',
        manufacturer: 'AudioTech Inc.',
        description: 'Portable Bluetooth speaker with rich 360° sound, IPX7 waterproof rating, and 24-hour battery life. Perfect for study sessions, outdoor activities, and travel.',
        bulletPoints: ['🔊 Rich 360° Immersive Sound', '💧 IPX7 Waterproof Rating', '🔋 24hr Battery Life', '📱 Bluetooth 5.3 Technology', '🎒 Portable with Carry Strap'],
        category: 'ELECTRONICS',
        subCategory: 'Speakers',
        pricing: { basePrice: 59.99, salePrice: 39.99, compareAtPrice: 79.99, savingsPercentage: 50, isOnSale: true, currency: 'USD' },
        totalQuantity: 220,
        condition: 'NEW',
        availability: 'IN_STOCK',
        rating: 4.6,
        reviewCount: 1890,
        isPrimeEligible: true,
        isBestSeller: false,
        isAmazonChoice: true,
        sellerId: 'user-004',
        sellerName: 'AudioTech Official',
        sellerRating: 4.8,
        images: [
            { id: 'img-1', url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop', thumbnailUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=100&h=100&fit=crop', altText: 'Bluetooth Speaker', isPrimary: true, order: 0 },
        ],
        dimensions: { length: 7, width: 3, height: 3, weight: 400, unit: 'in', weightUnit: 'g' },
        shipping: { freeShipping: true, estimatedDelivery: { standard: { minDays: 3, maxDays: 5, businessDays: true } }, shipsFrom: 'US', internationalShipping: true },
        amazonFeatures: { isPrimeEligible: true, isAmazonChoice: true, isBestSeller: false, isAmazonBrand: false, hasCoupon: false, isSubscribeAndSave: false, isClimatePledgeFriendly: true, isAlexaEnabled: false, isAmazonFresh: false, tradeInEligible: false },
        badges: [{ type: 'AMAZON_CHOICE', text: "Amazon's Choice" }, { type: 'SALE', text: '50% OFF' }],
        originCountry: 'China',
        createdAt: '2024-03-20T00:00:00Z',
        updatedAt: '2024-06-01T00:00:00Z',
    },
    {
        id: 'prod-025',
        asin: 'B08N5WRWOU',
        title: 'Digital Note-Taking Tablet - 10.1" HD Display with Stylus Pen',
        subtitle: 'Paperless Study & Work Solution',
        brand: 'StreamPro',
        manufacturer: 'StreamPro Tech',
        description: '10.1 inch digital tablet perfect for note-taking, drawing, reading PDFs, and online learning. Includes precise stylus pen and 64GB storage.',
        bulletPoints: ['📝 10.1" HD Clear Display', '🖊️ Includes Precise Stylus Pen', '💾 64GB Internal Storage', '📖 Perfect for PDFs & Note-Taking', '🔋 12hr Long Battery Life'],
        category: 'ELECTRONICS',
        subCategory: 'Tablets',
        pricing: { basePrice: 199.99, salePrice: 149.99, compareAtPrice: 249.99, savingsPercentage: 40, isOnSale: true, currency: 'USD' },
        totalQuantity: 100,
        condition: 'NEW',
        availability: 'IN_STOCK',
        rating: 4.3,
        reviewCount: 890,
        isPrimeEligible: true,
        isBestSeller: false,
        isAmazonChoice: false,
        sellerId: 'user-004',
        sellerName: 'StreamPro Official',
        sellerRating: 4.5,
        images: [
            { id: 'img-1', url: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop', thumbnailUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=100&h=100&fit=crop', altText: 'Digital Tablet', isPrimary: true, order: 0 },
        ],
        dimensions: { length: 10, width: 7, height: 0.3, weight: 450, unit: 'in', weightUnit: 'g' },
        shipping: { freeShipping: true, estimatedDelivery: { standard: { minDays: 3, maxDays: 5, businessDays: true } }, shipsFrom: 'US', internationalShipping: true },
        amazonFeatures: { isPrimeEligible: true, isAmazonChoice: false, isBestSeller: false, isAmazonBrand: false, hasCoupon: false, isSubscribeAndSave: false, isClimatePledgeFriendly: false, isAlexaEnabled: false, isAmazonFresh: false, tradeInEligible: false },
        badges: [{ type: 'SALE', text: '40% OFF' }],
        originCountry: 'China',
        createdAt: '2024-06-01T00:00:00Z',
        updatedAt: '2024-06-01T00:00:00Z',
    },
];

// Categories
export const mockCategories = [
    { id: 'cat-001', name: 'Electronics', slug: 'electronics', icon: '🖥️', description: 'Headphones, laptops, tablets & accessories' },
    { id: 'cat-002', name: 'Fashion', slug: 'fashion', icon: '👗', description: 'Coming Soon' },
    { id: 'cat-003', name: 'Home & Kitchen', slug: 'home-kitchen', icon: '🏠', description: 'Coming Soon' },
    { id: 'cat-004', name: 'Books', slug: 'books', icon: '📚', description: 'Coming Soon' },
    { id: 'cat-005', name: 'Sports & Outdoors', slug: 'sports-outdoors', icon: '⚽', description: 'Coming Soon' },
    { id: 'cat-006', name: 'Beauty', slug: 'beauty', icon: '💄', description: 'Coming Soon' },
    { id: 'cat-007', name: 'Toys & Games', slug: 'toys-games', icon: '🧸', description: 'Coming Soon' },
    { id: 'cat-008', name: 'Automotive', slug: 'automotive', icon: '🚗', description: 'Coming Soon' },
];

export const mockAdminDashboard = { totalUsers: 5, activeUsers: 4, totalProducts: 8, totalOrders: 2, totalRevenue: 609.90, newUsersToday: 1, pendingOrders: 0 };

export const mockUsers = [
    { id: 'user-001', email: 'admin@amazonclone.com', firstName: 'Admin', lastName: 'User', role: 'ADMIN', membershipTier: 'PRIME', isActive: true, createdAt: '2024-01-01T00:00:00Z' },
    { id: 'user-002', email: 'john@example.com', firstName: 'John', lastName: 'Doe', role: 'CUSTOMER', membershipTier: 'PRIME', isActive: true, createdAt: '2024-02-15T00:00:00Z' },
    { id: 'user-003', email: 'jane@example.com', firstName: 'Jane', lastName: 'Smith', role: 'CUSTOMER', membershipTier: 'FREE', isActive: true, createdAt: '2024-03-10T00:00:00Z' },
    { id: 'user-004', email: 'seller@amazonclone.com', firstName: 'Seller', lastName: 'One', role: 'SELLER', membershipTier: 'PRIME_BUSINESS', isActive: true, createdAt: '2024-01-20T00:00:00Z' },
    { id: 'user-005', email: 'inactive@example.com', firstName: 'Inactive', lastName: 'User', role: 'CUSTOMER', membershipTier: 'FREE', isActive: false, createdAt: '2024-04-01T00:00:00Z' },
];

export const mockCart = {
    id: 'cart-001', userId: 'user-002', items: [
        { id: 'cart-item-001', productId: 'prod-001', title: 'Wireless Headphones', brand: 'AudioTech', image: { url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=100&h=100&fit=crop' }, quantity: 2, unitPrice: 99.99, totalPrice: 199.98, isOnSale: true, inStock: true, maxQuantity: 10, isPrimeEligible: true, sellerName: 'AudioTech Official', addedAt: '2024-06-10T10:30:00Z' },
    ], subtotal: 199.98, itemCount: 2, total: 199.98,
};

export const mockWishlist = {
    id: 'wish-001', userId: 'user-002', name: 'My Wishlist', items: [
        { id: 'wish-item-001', productId: 'prod-008', product: { title: 'Digital Quran Pen', image: { url: 'https://images.unsplash.com/photo-1589998059171-988d0df3a8b3?w=100&h=100&fit=crop' }, brand: 'QuranTech', rating: 4.8 }, pricing: { currentPrice: 59.99, isOnSale: true, isPrimeEligible: true }, availability: 'IN_STOCK', priority: 'HIGH', quantity: 1 },
        { id: 'wish-item-002', productId: 'prod-024', product: { title: 'Bluetooth Speaker', image: { url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=100&h=100&fit=crop' }, brand: 'AudioTech', rating: 4.6 }, pricing: { currentPrice: 39.99, isOnSale: true, isPrimeEligible: true }, availability: 'IN_STOCK', priority: 'MEDIUM', quantity: 1 },
    ], itemCount: 2,
};

export const mockOrders = [
    { id: 'order-001', orderNumber: '113-8795423-9876254', status: 'DELIVERED', items: [{ title: 'Wireless Headphones', quantity: 2, totalPrice: 199.98, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=100&h=100&fit=crop' }], total: 199.98, createdAt: '2024-03-15T10:30:00Z' },
    { id: 'order-002', orderNumber: '113-8795423-9876255', status: 'SHIPPED', items: [{ title: 'Digital Quran Pen', quantity: 1, totalPrice: 59.99, image: 'https://images.unsplash.com/photo-1589998059171-988d0df3a8b3?w=100&h=100&fit=crop' }], total: 59.99, createdAt: '2024-06-14T08:00:00Z' },
];

export const mockDashboardStats = { totalOrders: 12, activeOrders: 3, totalSpent: 1234.56, wishlistItems: 5, reviewCount: 3 };